/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StatusTokenRouteImport } from './routes/status/$token'
import { Route as OnboardTokenRouteImport } from './routes/onboard/$token'
import { Route as EmployeeTokenRouteImport } from './routes/employee/$token'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as AuthDashboardRouteRouteImport } from './routes/_auth/dashboard/route'
import { Route as AuthDashboardIndexRouteImport } from './routes/_auth/dashboard/index'
import { Route as AuthAppIndexRouteImport } from './routes/_auth/app/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as AuthDashboardNewRouteImport } from './routes/_auth/dashboard/new'
import { Route as AuthDashboardIdIndexRouteImport } from './routes/_auth/dashboard/$id/index'
import { Route as AuthDashboardIdConfigRouteImport } from './routes/_auth/dashboard/$id/config'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusTokenRoute = StatusTokenRouteImport.update({
  id: '/status/$token',
  path: '/status/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardTokenRoute = OnboardTokenRouteImport.update({
  id: '/onboard/$token',
  path: '/onboard/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeTokenRoute = EmployeeTokenRouteImport.update({
  id: '/employee/$token',
  path: '/employee/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDashboardRouteRoute = AuthDashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthDashboardIndexRoute = AuthDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthDashboardRouteRoute,
} as any)
const AuthAppIndexRoute = AuthAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDashboardNewRoute = AuthDashboardNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthDashboardRouteRoute,
} as any)
const AuthDashboardIdIndexRoute = AuthDashboardIdIndexRouteImport.update({
  id: '/$id/',
  path: '/$id/',
  getParentRoute: () => AuthDashboardRouteRoute,
} as any)
const AuthDashboardIdConfigRoute = AuthDashboardIdConfigRouteImport.update({
  id: '/$id/config',
  path: '/$id/config',
  getParentRoute: () => AuthDashboardRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/signin': typeof SigninRoute
  '/terms': typeof TermsRoute
  '/dashboard': typeof AuthDashboardRouteRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/employee/$token': typeof EmployeeTokenRoute
  '/onboard/$token': typeof OnboardTokenRoute
  '/status/$token': typeof StatusTokenRoute
  '/dashboard/new': typeof AuthDashboardNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/': typeof AuthAppIndexRoute
  '/dashboard/': typeof AuthDashboardIndexRoute
  '/dashboard/$id/config': typeof AuthDashboardIdConfigRoute
  '/dashboard/$id/': typeof AuthDashboardIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/signin': typeof SigninRoute
  '/terms': typeof TermsRoute
  '/api/health': typeof ApiHealthRoute
  '/employee/$token': typeof EmployeeTokenRoute
  '/onboard/$token': typeof OnboardTokenRoute
  '/status/$token': typeof StatusTokenRoute
  '/dashboard/new': typeof AuthDashboardNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app': typeof AuthAppIndexRoute
  '/dashboard': typeof AuthDashboardIndexRoute
  '/dashboard/$id/config': typeof AuthDashboardIdConfigRoute
  '/dashboard/$id': typeof AuthDashboardIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/signin': typeof SigninRoute
  '/terms': typeof TermsRoute
  '/_auth/dashboard': typeof AuthDashboardRouteRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/employee/$token': typeof EmployeeTokenRoute
  '/onboard/$token': typeof OnboardTokenRoute
  '/status/$token': typeof StatusTokenRoute
  '/_auth/dashboard/new': typeof AuthDashboardNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_auth/app/': typeof AuthAppIndexRoute
  '/_auth/dashboard/': typeof AuthDashboardIndexRoute
  '/_auth/dashboard/$id/config': typeof AuthDashboardIdConfigRoute
  '/_auth/dashboard/$id/': typeof AuthDashboardIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy'
    | '/signin'
    | '/terms'
    | '/dashboard'
    | '/api/health'
    | '/employee/$token'
    | '/onboard/$token'
    | '/status/$token'
    | '/dashboard/new'
    | '/api/auth/$'
    | '/app/'
    | '/dashboard/'
    | '/dashboard/$id/config'
    | '/dashboard/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/signin'
    | '/terms'
    | '/api/health'
    | '/employee/$token'
    | '/onboard/$token'
    | '/status/$token'
    | '/dashboard/new'
    | '/api/auth/$'
    | '/app'
    | '/dashboard'
    | '/dashboard/$id/config'
    | '/dashboard/$id'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/privacy'
    | '/signin'
    | '/terms'
    | '/_auth/dashboard'
    | '/api/health'
    | '/employee/$token'
    | '/onboard/$token'
    | '/status/$token'
    | '/_auth/dashboard/new'
    | '/api/auth/$'
    | '/_auth/app/'
    | '/_auth/dashboard/'
    | '/_auth/dashboard/$id/config'
    | '/_auth/dashboard/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  SigninRoute: typeof SigninRoute
  TermsRoute: typeof TermsRoute
  ApiHealthRoute: typeof ApiHealthRoute
  EmployeeTokenRoute: typeof EmployeeTokenRoute
  OnboardTokenRoute: typeof OnboardTokenRoute
  StatusTokenRoute: typeof StatusTokenRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status/$token': {
      id: '/status/$token'
      path: '/status/$token'
      fullPath: '/status/$token'
      preLoaderRoute: typeof StatusTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboard/$token': {
      id: '/onboard/$token'
      path: '/onboard/$token'
      fullPath: '/onboard/$token'
      preLoaderRoute: typeof OnboardTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee/$token': {
      id: '/employee/$token'
      path: '/employee/$token'
      fullPath: '/employee/$token'
      preLoaderRoute: typeof EmployeeTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/dashboard/': {
      id: '/_auth/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthDashboardIndexRouteImport
      parentRoute: typeof AuthDashboardRouteRoute
    }
    '/_auth/app/': {
      id: '/_auth/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthAppIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/dashboard/new': {
      id: '/_auth/dashboard/new'
      path: '/new'
      fullPath: '/dashboard/new'
      preLoaderRoute: typeof AuthDashboardNewRouteImport
      parentRoute: typeof AuthDashboardRouteRoute
    }
    '/_auth/dashboard/$id/': {
      id: '/_auth/dashboard/$id/'
      path: '/$id'
      fullPath: '/dashboard/$id/'
      preLoaderRoute: typeof AuthDashboardIdIndexRouteImport
      parentRoute: typeof AuthDashboardRouteRoute
    }
    '/_auth/dashboard/$id/config': {
      id: '/_auth/dashboard/$id/config'
      path: '/$id/config'
      fullPath: '/dashboard/$id/config'
      preLoaderRoute: typeof AuthDashboardIdConfigRouteImport
      parentRoute: typeof AuthDashboardRouteRoute
    }
  }
}

interface AuthDashboardRouteRouteChildren {
  AuthDashboardNewRoute: typeof AuthDashboardNewRoute
  AuthDashboardIndexRoute: typeof AuthDashboardIndexRoute
  AuthDashboardIdConfigRoute: typeof AuthDashboardIdConfigRoute
  AuthDashboardIdIndexRoute: typeof AuthDashboardIdIndexRoute
}

const AuthDashboardRouteRouteChildren: AuthDashboardRouteRouteChildren = {
  AuthDashboardNewRoute: AuthDashboardNewRoute,
  AuthDashboardIndexRoute: AuthDashboardIndexRoute,
  AuthDashboardIdConfigRoute: AuthDashboardIdConfigRoute,
  AuthDashboardIdIndexRoute: AuthDashboardIdIndexRoute,
}

const AuthDashboardRouteRouteWithChildren =
  AuthDashboardRouteRoute._addFileChildren(AuthDashboardRouteRouteChildren)

interface AuthRouteRouteChildren {
  AuthDashboardRouteRoute: typeof AuthDashboardRouteRouteWithChildren
  AuthAppIndexRoute: typeof AuthAppIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthDashboardRouteRoute: AuthDashboardRouteRouteWithChildren,
  AuthAppIndexRoute: AuthAppIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  SigninRoute: SigninRoute,
  TermsRoute: TermsRoute,
  ApiHealthRoute: ApiHealthRoute,
  EmployeeTokenRoute: EmployeeTokenRoute,
  OnboardTokenRoute: OnboardTokenRoute,
  StatusTokenRoute: StatusTokenRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.tsx'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
