#!/usr/bin/env bash
# Setup functions: rclone init, B2 init, verify remotes
# Called via: grota setup rclone | grota setup b2 | grota verify remotes
set -euo pipefail

[[ "$(type -t log_info)" == "function" ]] || source "$(dirname "${BASH_SOURCE[0]}")/common.sh"

RCLONE_ENV_FILE="${RCLONE_ENV_FILE:-/etc/grota/rclone-env.sh}"

sanitize_email() {
  echo "$1" | tr '@.' '_'
}

# Convert remote name to rclone env var prefix (uppercase, hyphens to underscores)
env_prefix() {
  echo "$1" | tr '[:lower:]-' '[:upper:]_'
}

build_rclone_token() {
  local refresh_token="$1"
  jq -cn \
    --arg refresh "$refresh_token" \
    '{access_token: "", token_type: "Bearer", refresh_token: $refresh, expiry: "2000-01-01T00:00:00Z"}'
}

# Append env vars for a Drive remote to the env file
write_drive_env() {
  local name="$1" client_id="$2" client_secret="$3" scope="$4" token_json="$5"
  local prefix
  prefix=$(env_prefix "$name")

  cat >> "$RCLONE_ENV_FILE" <<EOF
# ${name}
export RCLONE_CONFIG_${prefix}_TYPE=drive
export RCLONE_CONFIG_${prefix}_CLIENT_ID='${client_id}'
export RCLONE_CONFIG_${prefix}_CLIENT_SECRET='${client_secret}'
export RCLONE_CONFIG_${prefix}_SCOPE='${scope}'
export RCLONE_CONFIG_${prefix}_TOKEN='${token_json}'

EOF
}

# Append env vars for a B2 remote to the env file
write_b2_env() {
  local name="$1" key_id="$2" app_key="$3"
  local prefix
  prefix=$(env_prefix "$name")

  cat >> "$RCLONE_ENV_FILE" <<EOF
# ${name}
export RCLONE_CONFIG_${prefix}_TYPE=b2
export RCLONE_CONFIG_${prefix}_ACCOUNT='${key_id}'
export RCLONE_CONFIG_${prefix}_KEY='${app_key}'

EOF
}

# -- grota setup rclone ----------------------------------------
cmd_setup_rclone() {
  init_logging "setup-rclone"
  require_cmd jq

  mkdir -p "$(dirname "$RCLONE_ENV_FILE")"
  require_env GOOGLE_CLIENT_ID GOOGLE_CLIENT_SECRET

  # Start fresh env file (preserve B2 section if setup b2 ran first)
  local b2_section=""
  if [[ -f "$RCLONE_ENV_FILE" ]]; then
    b2_section=$(sed -n '/^# b2_/,/^$/p' "$RCLONE_ENV_FILE" || true)
  fi

  cat > "$RCLONE_ENV_FILE" <<'HEADER'
#!/usr/bin/env bash
# Auto-generated by grota setup -- do not edit manually
HEADER

  local account_count
  account_count=$(cfg_account_count)
  log_info "Configuring rclone for $account_count accounts"

  local created=0
  for (( i=0; i<account_count; i++ )); do
    local email token remote_name rclone_token
    email=$(cfg_account_email "$i")
    token=$(cfg_account_token "$i")

    if [[ -z "$token" || "$token" == "null" ]]; then
      log_warn "Skipping $email -- no OAuth token"
      continue
    fi

    remote_name="gdrive_$(sanitize_email "$email")"
    rclone_token=$(build_rclone_token "$token")

    log_info "Configuring remote: $remote_name ($email)"
    write_drive_env "$remote_name" "$GOOGLE_CLIENT_ID" "$GOOGLE_CLIENT_SECRET" "drive.readonly" "$rclone_token"

    created=$((created + 1))
  done

  # Workspace admin remote (full scope for migration)
  local ws_token
  ws_token=$(cfg_workspace_token)
  if [[ -n "$ws_token" ]]; then
    local ws_rclone_token
    ws_rclone_token=$(build_rclone_token "$ws_token")

    log_info "Configuring workspace remote: workspace_drive"
    write_drive_env "workspace_drive" "$GOOGLE_CLIENT_ID" "$GOOGLE_CLIENT_SECRET" "drive" "$ws_rclone_token"

    created=$((created + 1))
    log_info "Created workspace_drive remote (full Drive scope)"
  fi

  # Restore B2 section if it existed
  if [[ -n "$b2_section" ]]; then
    echo "$b2_section" >> "$RCLONE_ENV_FILE"
  fi

  chmod 600 "$RCLONE_ENV_FILE"
  log_info "Created $created remotes in $RCLONE_ENV_FILE"
}

# -- grota setup b2 --------------------------------------------
cmd_setup_b2() {
  init_logging "setup-b2"
  require_cmd jq

  mkdir -p "$(dirname "$RCLONE_ENV_FILE")"

  local bucket_prefix
  bucket_prefix=$(cfg_b2_prefix)
  if [[ -z "$bucket_prefix" ]]; then
    log_fatal "b2.bucket_prefix not set in config JSON"
  fi

  # Preserve Drive section, rebuild B2
  local drive_section=""
  if [[ -f "$RCLONE_ENV_FILE" ]]; then
    drive_section=$(sed '/^# b2_/,/^$/d' "$RCLONE_ENV_FILE" || true)
    echo "$drive_section" > "$RCLONE_ENV_FILE"
  else
    cat > "$RCLONE_ENV_FILE" <<'HEADER'
#!/usr/bin/env bash
# Auto-generated by grota setup -- do not edit manually
HEADER
  fi

  for category in dokumenty projekty media; do
    local upper key_id_var app_key_var key_id app_key remote_name bucket_name
    upper=$(echo "$category" | tr '[:lower:]' '[:upper:]')
    key_id_var="B2_${upper}_KEY_ID"
    app_key_var="B2_${upper}_APP_KEY"

    key_id="${!key_id_var:-}"
    app_key="${!app_key_var:-}"

    # Fallback: single B2 key from config JSON
    if [[ -z "$key_id" ]]; then
      key_id=$(cfg_b2_key_id)
      app_key=$(cfg_b2_app_key)
    fi

    if [[ -z "$key_id" || -z "$app_key" ]]; then
      log_warn "Skipping B2 remote for $category -- no credentials"
      continue
    fi

    remote_name="b2_${category}"
    bucket_name="${bucket_prefix}-${category}"

    log_info "Configuring B2 remote: $remote_name -> $bucket_name"
    write_b2_env "$remote_name" "$key_id" "$app_key"

    log_info "Remote $remote_name created (bucket: $bucket_name)"
  done

  chmod 600 "$RCLONE_ENV_FILE"
  log_info "B2 remote setup complete"
}

# -- grota verify remotes --------------------------------------
cmd_verify_remotes() {
  init_logging "verify-remotes"
  require_cmd rclone jq

  local failed=0 passed=0 total=0

  verify_remote() {
    local remote="$1"
    local description="$2"
    total=$((total + 1))

    log_info "Verifying: $remote ($description)"

    if rclone lsd "${remote}:" --max-depth 0 --timeout 30s >/dev/null 2>&1; then
      log_info "  PASS: $remote"
      passed=$((passed + 1))
    else
      log_error "  FAIL: $remote"
      failed=$((failed + 1))
    fi
  }

  # Verify Drive remotes
  local account_count
  account_count=$(cfg_account_count)
  for (( i=0; i<account_count; i++ )); do
    local email remote_name
    email=$(cfg_account_email "$i")
    remote_name="gdrive_$(echo "$email" | tr '@.' '_')"
    verify_remote "$remote_name" "Google Drive: $email"
  done

  # Verify workspace remote
  if rclone listremotes | grep -q "^workspace_drive:$"; then
    verify_remote "workspace_drive" "Workspace admin Drive"
  fi

  # Verify B2 remotes
  local bucket_prefix
  bucket_prefix=$(cfg_b2_prefix)
  for category in dokumenty projekty media; do
    local remote_name bucket_name
    remote_name="b2_${category}"
    bucket_name="${bucket_prefix}-${category}"

    if ! rclone listremotes | grep -q "^${remote_name}:$"; then
      log_warn "Remote $remote_name not configured, skipping"
      continue
    fi

    total=$((total + 1))
    log_info "Verifying: $remote_name ($bucket_name)"

    if rclone lsd "${remote_name}:${bucket_name}" --max-depth 0 --timeout 30s >/dev/null 2>&1; then
      log_info "  PASS: $remote_name"
      passed=$((passed + 1))
    else
      log_error "  FAIL: $remote_name"
      failed=$((failed + 1))
    fi
  done

  log_info "Verification complete: $passed/$total passed, $failed failed"

  if (( failed > 0 )); then
    log_error "Some remotes failed verification"
    exit 1
  fi

  log_info "All remotes OK"
}
